name: build distribution

on: [push]

permissions:
  contents: read

jobs:
  build-distribution:
    name: build distribution
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: set up Python
        uses: actions/setup-python@v5

      - name: install pypa/build
        run: |
          python -m pip install --upgrade pip
          python -m pip install --requirement requirements.txt
          python -m pip install build

      - name: build a binary wheel and a source tarball
        run: python3 -m build

      - name: store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
