name: pytest windows

on: [push]

env:
  PYTHONPATH: /Users/runner/work/g2-sdk-python-grpc/g2-sdk-python-grpc/src

jobs:
  pytest-windows:
    name: "pytest OS: ${{ matrix.os }}; Python ${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # python-version: ["3.8", "3.9", "3.10", "3.11"]
        python-version: ["3.8", "3.11"]
        os: [windows-latest]

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: TODO - install senzing-tools
        run: echo "TODO - Run senzing-tools serve-grpc"
      # - name: Install Docker
      #   uses: docker-practice/actions-setup-docker@master
      #   timeout-minutes: 12
      # - name: gRPC service
      #   run: docker run --detach --env SENZING_TOOLS_ENABLE_ALL --publish 8261:8261 senzing/serve-grpc:latest
      # - name: Run pytest on tests
      #   run: pytest tests/ --verbose --capture=no --cov=src/senzing_grpc
