name: python-code-quality.yaml

on:
  - push
  - pull_request

jobs:
  python-code-quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.11"]
    name: "code-quality Python ${{ matrix.python-version }}"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --requirement requirements.txt
          python -m pip install black flake8 mypy psutil pylint pytest pytest_schema types-psutil types-protobuf
      - name: Black testing
        run: black --diff --check $(git ls-files '*.py' ':!:docs/source/*')
      - name: Pylint testing
        run: pylint $(git ls-files '*.py' ':!:docs/source/*' ':!:src/senzing_grpc/pb2_grpc/*')
      - name: flake8 testing
        run: flake8 $(git ls-files '*.py' ':!:docs/source/*' ':!:src/senzing_grpc/pb2_grpc/*')
      - name: Mypy testing
        run: mypy --follow-imports skip --strict $(git ls-files '*.py' ':!:docs/source/*' ':!:src/senzing_grpc/pb2_grpc/*')
