name: python-code-quality.yaml

on:
  - push
  - pull_request

jobs:
  python-code-quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.11"]
    name: "code-quality Python ${{ matrix.python-version }}"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --requirement requirements.txt
          python -m pip install black flake8  mypy pylint pytest pytest_schema psutil types-psutil
      - name: Black testing
        run: black --diff --check $(git ls-files '*.py')
      - name: Pylint testing
        run: pylint $(git ls-files '*.py' ':!:src/senzing/pb2_grpc/*')
      - name: flake8 testing
        run: flake8 $(git ls-files '*.py' ':!:src/senzing/pb2_grpc/*')
      - name: Mypy testing
        run: mypy --strict $(git ls-files '*.py' ':!:src/senzing/pb2_grpc/*' ':!:tests/*')
